# https://medium.com/@jwdobken/vue-with-docker-initialize-develop-and-build-51fad21ad5e6
# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'dockerized'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn dev"